name: sologather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  intl: ^0.18.1
  provider: ^6.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/header.jpg
